{"name": "Authorization test with incorrect password", "status": "passed", "start": 1713953698969, "stop": 1713953699113, "uuid": "6ea753b3-c8e6-489b-82a0-9c6e3c63fe50", "historyId": "82faacddf25850eefd1dfd8276f25d32", "testCaseId": "82faacddf25850eefd1dfd8276f25d32", "fullName": "tests.test_login_user.TestLoginUser#test_login_user_incorrect_password_error", "labels": [{"name": "feature", "value": "Checking user authorization"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "IZY-PC"}, {"name": "thread", "value": "25448-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}